create database DoAnWindows
go
use DoAnWindows
go
create table Question
(
	SttCau	int					primary key,
	CauHoi	nvarchar(500),
	CauA	nvarchar(500),
	CauB	nvarchar(500),
	CauC	nvarchar(500),
	CauD	nvarchar(500),
	DapAn	int
);
go
create table ThongTin
(
	Username	varchar(20)		primary key,
	Pass		varchar(50),
	HoTen		nvarchar(50),
	NgaySinh	nvarchar(20),
	DiaChi		nvarchar(50),
	SDT			nvarchar(20),
);
go
create table ThongKe
(
	username	varchar(20)		foreign key references ThongTin(Username),
	ThoiGian	varchar(30),
	DiemSo		int
);

insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (1, N'Phương tiện tham gia giao thông đường bộ" gồm những loại nào?', N'Phương tiện giao thông cơ giới đường bộ.', N'Phương tiện giao thông thô sơ đường bộ.', N'Xe máy chuyên dùng.', N'Cả ba loại trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (2, N'Người tham gia giao thông đường bộ" gồm những thành phần nào?', N'Người điều khiển, người sử dụng phương tiện tham gia giao thông đường bộ.', N'Người điều khiển, dẫn dắt súc vật.', N'Người đi bộ trên đường bộ.', N'Cả ba thành phần nêu trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (3, N'Khái niệm "đường bộ" được hiểu như thế nào là đúng ?', N'Đường bộ" gồm: Đường, cầu đường bộ, hầm đường bộ.', N'Đường bộ" gồm: Đường, cầu đường bộ, hầm đường bộ, bến phà đường bộ.', null, null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (4, N'Khái niệm "Phần đường xe chạy" được hiểu như thế nào là đúng?', N'Là phần của đường bộ được sử dụng cho các phương tiện giao thông qua lại.', N'Là phần của đường bộ được sử dụng cho các phương tiện giao thông qua lại, dải đất dọc hai bên đường để đảm bảo an toàn giao thông.', N'Cả hai ý trên.', null, 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (5, N'Khái niệm "Công trình đường bộ" được hiểu như thế nào là đúng ?', N'Công trình đường bộ" gồm: Đường bộ, nơi dừng xe, đỗ xe trên đường, đèn tím hiệu, cọc tiêu, biển báo hiệu, dải phân cách.', N'Công trình đường bộ" gồm: Đường bộ, nơi dừng xe, đỗ xe trên đường, đèn tín hiệu, cọc tiêu, biển báo hiệu, dải phân cách, hệ thống thoát nước và công trình, thiết bị phụ trợ khác.', null, null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (6, N'Khái niệm "Làn đường" được hiểu như thế nào là đúng?', N'Là một phần của phần đường xe chạy được chia theo chiều dọc của đường.', N'Là một phần của phần đường xe chạy được chia theo chiều dọc của đường, có bề rộng đủ cho xe chạy an toàn.', null , null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (7, N'Khái niệm "Khổ giới hạn của đường bộ" được hiểu như thế nào là đúng?', N'Là khoảng trống có kích thước giới hạn về chiều cao, chiều rộng của đường, cầu, hầm trên đường bộ để các xe kể cả hàng hoá xếp trên xe đi qua được an toàn.', N'Là khoảng trống có kích thước giới hạn về chiều rộng của đường, cầu, hầm trên đường bộ để các xe kể cả hàng hoá xếp trên xe đi qua được an toàn.', N'Là khoảng trống có kích thước giới hạn về chiều cao, chiều rộng của đường, cầu, hầm trên đường bộ để các xe đi qua được an toàn.', null, 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (8, N'Khái niệm "Dải phân cách"được hiểu như thế nào là đúng?', N'Là bộ phận của đường để phân chia mặt đường thành hai chiều chạy riêng biệt.', N'Là bộ phận của đường để phân chia phần đường của xe cơ giới và xe thô sơ.', N'Cả hai ý trên.', null, 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (9, N'Có mấy loại dải phân cách?', N'Loại cố định.', N'Loại di động.', N'Cả hai loại trên.', null, 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (10, N'Khi điều khiển xe qua cầu, qua phà cần chú ý những điểm gì?', N'Chấp hành nghiêm chỉnh các biển báo hiệu, tín hiệu nếu có.', N'Phải tuyệt đối tuân thủ theo sự điều khiển chỉ dẫn của người gác cầu hoặc nhân viên bến phà.', N'Cả 2 ý nêu trên.', null, 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (11, N'Phương tiện giao thông đường bộ" gồm những loại nào?', N'Phương tiện giao thông cơ giới đường bộ.', N'Phương tiện giao thông thô sơ đường bộ.', N'Cả hai loại nêu trên.', null, 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (12, N'Phương tiện giao thông cơ giới đường bộ" gồm những loại nào?', N'Ô-tô, máy kéo, xe mô tô hai bánh, xe mô tô ba bánh, xe gắn máy.', N'Ô-tô, máy kéo, xe mô tô hai bánh, xe mô tô ba bánh, xe gắn máy và các loại xe tương tự, kể cả xe cơ giới dùng cho người tàn tật.', null, null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (13, N'Phương tiện giao thông thô sơ đường bộ" gồm những loại nào?', N'Những loại xe không di chuyển bằng sức động cơ như xe đạp, xe xích lô.', N'Xe súc vật kéo và các loại xe tương tự.', N'Cả hai ý trên.', null, 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (14, N'Người điều khiển phương tiện tham gia giao thông" gồm những thành phần nào? ', N'Người điều khiển xe cơ giới.', N'Người điều khiển xe thô sơ.', N'Người điều khiển xe máy chuyên dùng tham gia giao thông đường bộ.', N'Cả ba thành phần nêu trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (15, N'Người điều khiển giao thông" gồm những thành phần nào?', N'Người điều khiển phương tiện tham gia giao thông.', N'Cảnh sát giao thông, người được giao nhiệm vụ hướng dẫn giao thông tại nơi thi công, nơi ùn tắc giao thông, ở bến phà, tại cầu đường bộ đi chung với đường sắt.', null, null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (16, N'Người tham gia giao thông phải làm gì để đảm bảo an toàn giao thông đường bộ? ', N'Phải nghiêm chỉnh chấp hành quy tắc giao thông.', N'Phải giữ gìn an toàn cho mình và cho người khác.', N'Cả hai ý trên.', null, 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (17, N'Bảo đảm an toàn giao thông đường bộ là trách nhiệm của ai?', N'Là trách nhiệm của ngành Giao thông vận tải.', N'Là trách nhiệm của các cơ quan, tổ chức, cá nhân và của toàn xã hội.', N'Là trách nhiệm của Cảnh sát giao thông.', null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (18, N'Mọi hành vi vi phạm Luật giao thông đường bộ được xử lý như thế nào?', N'Phải được xử lý nghiêm minh.', N'Phải được xử lý kịp thời.', N'Phải được xử lý đúng pháp luật.', N'Cả ba ý trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (19, N'Người lái xe đang điều khiển xe trên đường mà trong máu có nồng độ cồn vượt quá bao nhiêu thì bị nghiêm cấm?', N'Nồng độ cồn vượt quá 60 miligam/100 mililít máu.', N'Nồng độ cồn vượt quá 80 miligam/100 mililít máu.', N'Nồng độ cồn vượt quá 100 miligam/100 mililít máu.', null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (20, N'Người lái xe đang điều khiển xe trên đường mà trong khí thở có nồng độ cồn vượt quá bao nhiêu thì bị nghiêm cấm?', N'Nồng độ cồn vượt quá 40miligam/1 lít khí thở.', N'Nồng độ cồn vượt quá 60miligam/1 lít khí thở.', N'Nồng độ cồn vượt quá 80miligam/1 lít khí thở.', null, 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (21, N'Người tham gia giao thông phải đi như thế nào là đúng quy tắc giao thông?', N'Đi bên phải theo chiều đi của mình.', N'Đi đúng phần đường quy định.', N'Chấp hành hệ thống báo hiệu đường bộ.', N'Tất cả các ý trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (22, N'Biển báo hiệu đường bộ gồm những nhóm nào, ý nghĩa của từng nhóm?', N'Nhóm biển báo cấm để biểu thị các điều cấm, nhóm biển báo nguy hiểm để cảnh báo các tình huống nguy hiểm có thể xảy ra.', N'Nhóm hiệu lệnh để báo các hiệu lệnh phải thi hành, Nhóm biển chỉ dẫn để chỉ dẫn hướng đi hoặc các điều cần biết.', N'Nhóm biển phụ để thuyết minh bổ sung các loại biển báo cấm, biển báo nguy hiểm, biển hiệu lệnh và biển chỉ dẫn.', N'Tất cả các nhóm nêu trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (23, N'Người lái xe phải làm gì khi điều kiển xe vào đường cao tốc?', N'Phải có tín hiệu xin vào và phải nhường đường cho xe đang chạy trên đường.', N'Khi thấy an toàn mới cho xe nhập vào dòng xe ở làn đường sát mép ngoài.', N'Nếu có làn đường tăng tốc thì phải cho xe chạy trên làn đường đó trước khi vào các làn đường của đường cao tốc.', N'Tất cả các ý nêu trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (24, N'Khi điều khiển xe qua cầu hẹp cần chú ý những điểm gì?', N'Dùng số thấp giữ đều ga cho xe qua từ từ, không được đi sát rìa cầu, không tăng ga đột ngột, đổi số hoặc phanh gấp trên cầu.', N'Dùng số phù hợp, cho xe qua từ từ, không được đi sát rìa cầu, không tăng ga đột ngột, đổi số hoặc phanh gấp trên cầu.', null, null, 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (25, N'Khi điều khiển xe trên đường trơn cần chú ý những điểm gì?', N'Giữ vững tay lái cho xe đi đúng vệt bánh xe đi trước, sử dụng số thấp đi chậm, giữ đều ga, đánh lái ngoặt và phanh gấp khi cần thiết.', N'Giữ vững tay lái cho xe đi đúng vệt bánh xe đi trước, sử dụng số thấp đi chậm, giữ đều ga, không lấy nhiều lái, không đánh lái ngoặt và phanh gấp.', null, null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (26, N'Người điều khiển phưong tiện tham gia giao thông trong hầm đường bộ phải tuân thủ những điểm gì là đúng quy tắc giao thông?', N'Xe cơ giới phải bật đèn ngay cả khi đường hầm sáng, xe thô sơ phải có đèn hoặc có vật phát sáng báo hiệu.', N'Chỉ được dừng xe, đỗ xe ở những nơi quy định.', N'Không được quay đầu xe, lùi xe.', N'Tất cả các ý trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (27, N'Trường hợp xe kéo xe và kéo rơmoóc, những hành vi nào bị cấm?', N'Xe kéo rờ moóc, xe sơ mi rơ moóc kéo theo rơ moóc hoặc xe khác.', N'Chở người trên xe được kéo.', N'Xe ôtô kéo theo xe thô sơ, xe mô tô hai bánh, xe mô tô ba bánh, xe gắn máy hoặc kéo lê vật trên đường.', N'Tất cả các ý nêu trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (28, N'Người tham gia giao thông khi phát hiện công trình đường bộ bị hư hỏng hoặc bị xâm hại, phải có những nghĩa vụ gì?', N'Kịp thời báo cáo cho chính quyền địa phương.', N'Kịp thời báo cáo cho cơ quan quản lý đường bộ hoặc cơ quan công an nơi gần nhất, để xử lý.', N'Trong trường hợp cần thiết có biện pháp báo hiệu ngay cho người tham gia giao thông biết.', N'Tất cả các nghĩa vụ trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (29, N'Khi điều khiển xe giảm số cần chú ý những điểm gì?', N'Không được nhìn xuống buồng lái, cần phải giảm theo thứ tự từ cao đến thấp, phối hợp các động tác phải nhịp nhàng, chính xác.', N'Không được nhìn xuống buồng lái, cần phải giảm theo thứ tự từ cao đến thấp, phối hợp các động tác phải nhịp nhàng, chính xác, vù ga phải phù hợp với tốc độ.', null, null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (30, N'Chủ xe và người lái xe bánh xích, xe quá khổ, quá tải có trách nhiệm gì khi cho xe tham gia giao thông đường bộ?', N'Xin phép lưu hành đặc biệt.', N'Chịu sự kiểm soát về tải trọng và khổ giới hạn của cơ quan quản lý đường bộ.', N'Chịu phí tổn gia cố, bảo vệ công trình giao thông, hạ tải, xếp lại hàng hoá, tự bảo quản hàng đã bị dỡ xuống và nộp phạt theo quy định.', N'Tất cả các trách nhiệm trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (31, N'Những người có mặt tại nơi xảy ra tai nạn giao thông có trách nhiệm gì?', N'Bảo vệ hiện trường, giúp đỡ, cứu chữa kịp thời, bảo vệ tài sản của người bị nạn.', N'Báo tin ngay cho cơ quan công an hoặc Uỷ ban nhân dân nơi gần nhất.', N'Cung cấp thông tin sát thực về vụ tai nạn theo yêu cầu của cơ quan công an.', N'Tất cả ba trách nhiệm nêu trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (32, N'Trên đường giao thông, khi hiệu lệnh của người điều khiển giao thông trái với hiệu lệnh của đèn hoặc biển báo thì người tham gia giao thông phải chấp hành theo hiệu lệnh nào?', N'Hiệu lệnh của người điều khiển giao thông.', N'Hiệu lệnh của đèn điều khiển giao thông.', N'Hiệu lệnh của biển báo hiệu đường bộ.', null, 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (33, N'Khi ở một khu vực đồng thời có đặt biển báo cố định và biển báo tạm thời mà ý nghĩa hiệu lực khác nhau, thì người lái xe phải chấp hành theo hiệu lệnh nào?', N'Biển báo cố định.', N'Biển báo tạm thời.', null, null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (34, N'Cơ quan nào quy định tải trọng, khổ giới hạn của đường bộ?', N'Bộ Giao thông vận tải.', N'Cục Đường bộ Việt Nam.', N'Sở Giao thông vận tải, Giao thông công chính các tỉnh thành phố.', N'Cảnh sát giao thông.', 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (35, N'Trong trường hợp đặc biệt, xe quá tải trọng, quá khổ giới hạn của đường bộ khi lưu hành phải xin giấy phép của cơ quan nào?', N'Cơ quan Cảnh sát giao thông có thẩm quyền.', N'Cơ quan Quản lý giao thông có thẩm quyền.', N'Uỷ ban nhân dân tỉnh.', null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (36, N'Hai xe đi ngược chiều nhường đường khi tránh nhau như thế nào là đúng quy tắc giao thông?', N'Nơi đường hẹp chỉ đủ cho một xe chạy và có chỗ tránh xe thì xe nào ở gần chỗ tránh hơn phải vào vị trí tránh,nhường đường cho xe kia đi.', N'Xe xuống dốc phải nhường đường cho xe lên dốc.', N'Xe nào có chướng ngại vật phía trước phải nhường đường cho xe kia đi.', N'Tất cả các ý nêu trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (37, N'Xe ôtô tham gia giao thông trên đường phố có bắt buộc phải có bộ phận giảm thanh, giảm khói không?', N'Không bắt buộc.', N'Bắt buộc.', null, null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (38, N'Xe ôtô tham gia giao thông trên đường phải có các loại đèn gì?', N'Đèn chiếu sáng gần và xa.', N'Đèn soi biển số.', N'Đèn báo hãm và đèn tín hiệu.', N'Có đủ các loại đèn ghi trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (39, N'Ban đêm, xe cơ giới đi ngược chiều gặp nhau, đèn chiếu sáng phải sử dụng như thế nào là đúng quy tắc giao thông?', N'Chuyển từ đèn chiếu gần sang đèn chiếu xa.', N'Phải chuyển từ đèn chiếu xa sang đèn chiếu gần.', null, null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (40, N'Xe cơ giới 2-3 bánh có được kéo đẩy nhau hoặc vật gì khác trên đường không? ', N'Được phép.', N'Tuỳ trường hợp.', N'Tuyệt đối không.', null, 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (41, N'Trong đô thị, đoạn đường có dải phân cách cố định, khi không có biển hạn chế tốc độ, với điều kiện đường khô ráo và thời tiết bình thường, loại phương tiện nào chạy với tốc độ tối đa 50km/h?', N'Xe xích lô máy, xe gắn máy.', N'Các loại xe con, xe taxi đến 9 chỗ ngồi.', N'Xe tải có tải trọng từ 3.500 kg trở lên, xe ôtô chở người trên 30 chỗ ngồi.', N'Xe môtô 2-3 bánh, xe tải có tải trọng dưới 3.500kg, xe ôtô chở người từ 10 đến 30 chỗ ngồi.', 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (42, N'Trong đô thị, đoạn đường có dải phân cách cố định, khi không có biển hạn chế tốc độ, với điều kiện đường khô ráo và thời tiết bình thường, loại phương tiện nào chạy với tốc độ tối đa 40km/h?', N'Xe xích lô máy, xe gắn máy.', N'Các loại xe con, xe taxi đến 9 chỗ ngồi.', N'Xe tải có tải trọng từ 3.500 kg trở lên, xe ôtô chở người trên 30 chỗ ngồi.', N'Xe môtô 2-3 bánh, xe tải có tải trọng dưới 3.500kg, xe ôtô chở người từ 10 đến 30 chỗ ngồi.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (43, N'Trong đô thị, đoạn đường có dải phân cách cố định, khi không có biển hạn chế tốc độ, với điều kiện đường khô ráo và thời tiết bình thường, loại phương tiện nào chạy với tốc độ tối đa 35km/h?', N'Xe xích lô máy, xe gắn máy.', N'Các loại xe con, xe taxi đến 9 chỗ ngồi.', N'Xe tải có tải trọng từ 3.500 kg trở lên, xe ôtô chở người trên 30 chỗ ngồi.', N'Xe môtô 2-3 bánh, xe tải có tải trọng dưới 3.500kg, xe ôtô chở người từ 10 đến 30 chỗ ngồi.', 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (44, N'Trong đô thị, đoạn đường có dải phân cách cố định, khi không có biển hạn chế tốc độ, với điều kiện đường khô ráo và thời tiết bình thường, loại phương tiện nào chạy với tốc độ tối đa 30km/h?', N'Xe xích lô máy, xe gắn máy.', N'Các loại xe con, xe taxi đến 9 chỗ ngồi.', N'Xe tải có tải trọng từ 3.500 kg trở lên, xe ôtô chở người trên 30 chỗ ngồi.', N'Xe môtô 2-3 bánh, xe tải có tải trọng dưới 3.500kg, xe ôtô chở người từ 10 đến 30 chỗ ngồi.', 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (45, N'Trong đô thị, đoạn đường không có biển hạn chế tốc độ, với điều kiện đường khô ráo và thời tiết bình thường, loại phương tiện nào chạy với tốc độ tối đa 20km/h?', N'Xe xích lô máy, xe gắn máy.', N'Các loại xe con, xe taxi đến 9 chỗ ngồi.', N'Xe tải có tải trọng từ 3.500 kg trở lên, xe ôtô chở người trên 30 chỗ ngồi.', N'Xe môtô 2-3 bánh, xe tải có tải trọng dưới 3.500kg, xe ôtô chở người từ 10 đến 30 chỗ ngồi.', 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (46, N'Trong đô thị, đoạn đường không có dải phân cách cố định, khi không có biển hạn chế tốc độ, với điều kiện đường khô ráo và thời tiết bình thường, loại phương tiện nào chạy với tốc độ tối đa 30km/h?', N'Xe xích lô máy, xe gắn máy.', N'Các loại xe con, xe taxi đến 9 chỗ ngồi.', N'Xe tải có tải trọng từ 3.500 kg trở lên, xe ôtô chở người trên 30 chỗ ngồi.', N'Xe môtô 2-3 bánh, xe tải có tải trọng dưới 3.500kg, xe ôtô chở người từ 10 đến 30 chỗ ngồi.', 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (47, N'Trong đô thị, đoạn đường không có dải phân cách cố định, khi không có biển hạn chế tốc độ, với điều kiện đường khô ráo và thời tiết bình thường, loại phương tiện nào chạy với tốc độ tối đa 35km/h?', N'Xe xích lô máy, xe gắn máy.', N'Các loại xe con, xe taxi đến 9 chỗ ngồi.', N'Xe tải có tải trọng từ 3.500 kg trở lên, xe ôtô chở người trên 30 chỗ ngồi.', N'Xe môtô 2-3 bánh, xe tải có tải trọng dưới 3.500kg, xe ôtô chở người từ 10 đến 30 chỗ ngồi.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (48, N'Trong đô thị, đoạn đường không có dải phân cách cố định, khi không có biển hạn chế tốc độ, với điều kiện đường khô ráo và thời tiết bình thường, loại phương tiện nào chạy với tốc độ tối đa 45km/h?', N'Xe xích lô máy, xe gắn máy.', N'Các loại xe con, xe taxi đến 9 chỗ ngồi.', N'Xe tải có tải trọng từ 3.500 kg trở lên, xe ôtô chở người trên 30 chỗ ngồi.', N'Xe môtô 2-3 bánh, xe tải có tải trọng dưới 3.500kg, xe ôtô chở người từ 10 đến 30 chỗ ngồi.', 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (49, N'Trong đô thị, đoạn đường không có dải phân cách cố định, khi không có biển hạn chế tốc độ, với điều kiện đường khô ráo và thời tiết bình thường, loại phương tiện nào chạy với tốc độ tối đa 25km/h?', N'Xe xích lô máy, xe gắn máy.', N'Các loại xe con, xe taxi đến 9 chỗ ngồi.', N'Xe tải có tải trọng từ 3.500 kg trở lên, xe ôtô chở người trên 30 chỗ ngồi.', N'Xe môtô 2-3 bánh, xe tải có tải trọng dưới 3.500kg, xe ôtô chở người từ 10 đến 30 chỗ ngồi.', 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (50, N'Trên đường ngoài đô thị có dải phân cách cố định, trừ đường cao tốc, khi không có biển báo hạn chế tốc độ, với điều kiện đường khô ráo và thời tiết bình thường, loại phương tiện nào chạy với tốc độ tối đa 80km/h?', N'Xe xích lô máy, xe gắn máy.', N'Các loại xe con, xe taxi đến 9 chỗ ngồi.', N'Xe tải có tải trọng từ 3.500 kg trở lên, xe ôtô chở người trên 30 chỗ ngồi.', N'Xe tải có tải trọng từ 3.500 kg trở lên, xe ôtô chở người trên 30 chỗ ngồi.', 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (51, N'Trên đường ngoài đô thị có dải phân cách cố định, trừ đường cao tốc, khi không có biển hạn chế tốc độ, với điều kiện đường khô ráo và thời tiết bình thường, loại phương tiện nào chạy với tốc độ tối đa 60km/h?', N'Xe xích lô máy, xe gắn máy.', N'Các loại xe con, xe taxi đến 9 chỗ ngồi.', N'Xe tải có tải trọng từ 3.500 kg trở lên, xe ôtô chở người trên 30 chỗ ngồi.', N'Xe môtô 2-3 bánh, xe tải có tải trọng dưới 3.500kg, xe ôtô chở người từ 10 đến 30 chỗ ngồi.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (52, N'Trên đường ngoài đô thị có dải phân cách cố định, trừ đường cao tốc, khi không có biển hạn chế tốc độ, với điều kiện đường khô ráo và thời tiết bình thường, loại phương tiện nào chạy với tốc độ tối đa 50km/h?', N'Xe xích lô máy, xe gắn máy.', N'Các loại xe con, xe taxi đến 9 chỗ ngồi.', N'Xe tải có tải trọng từ 3.500 kg trở lên, xe ôtô chở người trên 30 chỗ ngồi.', N'Xe môtô 2-3 bánh, xe tải có tải trọng dưới 3.500kg, xe ôtô chở người từ 10 đến 30 chỗ ngồi.', 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (53, N'Trên đường ngoài đô thị không có dải phân cách cố định, trừ đường cao tốc, khi không có biển hạn chế tốc độ, với điều kiện đường khô ráo và thời tiết bình thường, loại phương tiện nào chạy với tốc độ tối đa 50km/h?', N'Xe xích lô máy, xe gắn máy.', N'Các loại xe con, xe taxi đến 9 chỗ ngồi.', N'Xe tải có tải trọng từ 3.500 kg trở lên, xe ôtô chở người trên 30 chỗ ngồi.', N'Xe môtô 2-3 bánh, xe tải có tải trọng dưới 3.500kg, xe ôtô chở người từ 10 đến 30 chỗ ngồi.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (54, N'Trong khu dân cư, ở nơi nào cho phép người lái xe quay đầu xe?', N'ở nơi có đường giao nhau và những chỗ có biển báo cho phép quay đầu xe.', N'ở nơi có đường rộng để cho các loại xe chạy hai chiều.', N'ở bất cứ nơi nào.', null, 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (55, N'Ở những nơi nào cấm quay đầu xe?', N'ở phần đường dành cho người đi bộ qua đường.', N'Trên cầu, đầu cầu, gầm cầu vượt, ngầm, trong hầm đường bộ, tại nơi đường bộ giao cắt đường sắt.', N'Đường hẹp, đoạn đường cong tầm nhìn bị che khuất.', N'Tất cả các trường hợp nêu trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (56, N'Khi lùi xe người lái phải làm gì để bảo đảm an toàn?', N'Quan sát phía sau và cho lùi xe.', N'Lợi dụng nơi đường giao nhau đủ chiều rộng để lùi.', N'Phải quan sát phía sau, có tín hiệu cần thiết và chỉ khi nào thấy không nguy hiểm mới được lùi.', null, 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (57, N'ở những nơi nào cấm lùi xe?', N'Ở khu vực cấm dừng và trên phần đường dành cho người đi bộ qua đường.', N'Nơi đường bộ giao nhau,đường bộ giao cắt đường sắt, nơi tầm nhìn bị che khuất, trong hầm đường bộ.', N'Tất cả những trường hợp.', null, 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (58, N'Trên đường có nhiều làn đường cho xe chạy cùng chiều được phân biệt bằng vạch kẻ phân làn đường, người lái xe cho xe chạy như thế nào là đúng quy tắc giao thông?', N'Cho xe chạy trên bất kỳ làn đường nào, khi chuyển làn phải có đèn tín hiệu báo trước, phải bảo đảm an toàn.', N'Phải cho xe chạy trong một làn đường và chỉ được chuyển làn đường ở những nơi cho phép, khi chuyển làn đường phải có tín hiệu báo trướcvà phải đảm bảo an toàn.', null, null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (59, N'Trường hợp đặc biệt phải dùng xe vận tải hàng hoá để chở người thì cơ quan nào quy định?', N'Chính phủ.', N'Bộ Giao thông vận tải.', N'Uỷ ban nhân dân tỉnh, thành phố trực thuộc trung ương.', null, 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (60, N'Khi vượt xe khác phải đảm bảo những điều kiện gì?', N'Không có chướng ngại vật ở phía trước, không có xe chạy ngược chiều trong đoạn đường định vượt.', N'Xe chạy trước không có tín hiệu vượt xe khác và đã tránh về bên phải, xe vượt phải vượt về bên trái (trừ các trường hợp đặc biệt).', N'Phải báo hiệu bằng đèn hoặc còi, trong đô thị và khu đông dân từ 22h đến 5h chỉ được báo hiệu xin vượt bằng đèn.', N'Tất cả những điều kiện trên', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (61, N'Khi điều khiển xe tăng số cần chú ý những điểm gì?', N'Không được nhìn xuống buồng lái, cần phải tăng thứ tự từ thấp đến cao, phối hợp các động tác phải nhịp nhàng, chính xác.', N'Không được nhìn xuống buồng lái, cần phải tăng theo thứ tự từ thấp đến cao, phối hợp các động tác phải nhịp nhàng, chính xác, vù ga phải phù hợp với tốc độ.', null, null, 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (62, N'Xe sau có thể vượt lên bên phải xe khác đang chạy phía trước trong trường hợp nào? ', N'Khi xe phía trước có tín hiệu rẽ trái hoặc đang rẽ trái.', N'Khi xe điện đang chạy giữa đường.', N'Khi xe chuyên dùng đang làm việc trên đường mà không thể vượt bên trái được.', N'Tất cả những trường hợp trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (63, N'Khi đang chạy dưới gầm cầu vượt, đường vòng, đầu dốc người lái xe muốn vượt xe khác thì phải xử lý như thế nào?', N'Nháy đèn pha kết hợp với tín hiệu còi cho xe trước biết để xe mình vượt.', N'Tuyệt đối không được vượt.', null, null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (64, N'Tại nơi đường sắt giao cắt đường bộ quyền ưu tiên thuộc về phương tiện nào? ', N'Xe nào đi bên phải không bị vướng thì được quyền đi trước.', N'Xe nào ra tín hiệu xin đường trước thì xe được đi trước.', N'Quyền ưu tiên thuộc về phương tiện đường sắt.', null, 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (65, N'Tại sao nơi đường bộ giao cắt đường sắt chỉ có đèn tín hiệu hoặc chuông báo hiệu, khi đèn tín hiệu màu đỏ đã bật sáng hoặc có tiếng chuông báo hiệu, người tham gia giao thông phải dừng lại và giữ khoảng cách tối thiểu bao nhiêu mét tính từ ray gần nhất?', N'5,00m.', N'3,00m.', N'4,00m.', N'2,00m.', 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (66, N'Khi qua đường giao nhau, thứ tự ưu tiên xe nào được đi trước là đúng quy tắc giao thông?', N'Xe cứu thương đang chở bệnh nhân cấp cứu hoặc đi đón bệnh nhân cấp cứu, đoàn xe tang.', N'Xe quân sự, xe công an nhân dân đi làm nhiệm vụ đặc biệt khẩn cấp, đoàn xe có cảnh sát đi dẫn đường.', N'Xe chữa cháy đi làm nhiệm vụ.', null, 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (67, N'Tại nơi đường giao nhau có báo hiệu đi theo vòng xuyến, người điều khiển phương tiện phải nhường đường như thế nào?', N'Ưu tiên bên phải.', N'Xe báo hiệu xin đường trước xe đó được đi trước.', N'Phải nhường đường cho xe đi bên trái.', null, 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (68, N'Tại nơi đường giao nhau giữa đường không ưu tiên và đường ưu tiên hoặc giữa đường nhánh và đường chính người lái xe phải xử lý như thế nào?', N'Nhường đường cho xe chạy ở bên phải mình tới.', N'Nhường đường cho xe chạy ở bên trái mình tới.', N'Nhường đường cho xe đi trên đường ưu tiên hoặc đường chính từ bất kỳ hướng nào tới.', null, 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (69, N'Những loại xe nào khi đi làm nhiệm vụ khẩn cấp có tín hiệu còi, cờ, đèn theo quy định. không bị hạn chế tốc độ?', N'Xe chữa cháy, xe hộ đê, xe công an, xe quân đội.', N'Xe chữa cháy, xe quân sự, xe công an, xe cứu thương.', N'Xe chữa cháy, xe quân sự, xe công an, xe cứu thương, xe hộ đê, đoàn xe có cảnh sát dẫn đường.', null, 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (70, N'Những loại xe nào khi làm nhiệm vụ khẩn cấp có tín hiệu còi, cờ, đèn theo quy định. có thể đi vào đường ngược chiều và chỉ phải tuân theo chỉ dẫn của người điều khiển giao thông?', N'Xe chữa cháy, xe quân sự, xe công an, xe cứu thương, xe hộ đê, đoàn xe có cảnh sát dẫn đường.', N'Xe chữa cháy, xe quân sự, xe công an, xe cứu thương.', N'Xe ngoại giao, đoàn xe tang, xe cứu thương, xe quân sự, xe công an, xe chữa cháy.', null, 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (71, N'Khi gặp một đoàn xe, một đoàn người có tổ chức, người lái xe có được phép cho xe chạy cắt ngang không?', N'Không được phép.', N'Được phép.', null, null, 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (72, N'Xe kéo nhau trên nhau trên đường đèo dốc, qua phà, cầu phao hoặc cầu treo nếu bộ phận hãm của xe được kéo đã mất hiệu lực thì phải dùng cách loại nào để kéo nhau?', N'Dùng dây cáp có độ dài 10m.', N'Dùng dây cáp có độ dài 5m.', N'Dùng thanh nối cứng.', null, 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (73, N'Người lái xe cần phải giảm tốc độ tới mức không nguy hiểm (có thể dừng lại một cách an toàn) trong các trường hợp nào?', N'Khi có báo hiệu hạn chế tốc độ hoặc có chướng ngại vật trên đường, khi tầm nhìn bị hạn chế.', N'Khi qua nơi đường giao nhau, nơi đường bộ giao cắt đường sắt, đường vòng, đoạn đường gồ ghề, trơn trượt, cát bụi.', N'Khi qua cầu, cống hẹp, khi lên gần đỉnh dốc, khi xuống dốc, khi qua trường học, nơi tập trung đông người, nơi đông dân, có nhà cửa gần đường.', N'Tất cả các hành vi trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (74, N'Trên xe vận tải có hàng hoá hoặc xe có kéo theo rơ-moóc ngoài người lái xe và phụ xe được phép trở thêm bao nhiêu người?', N'4 người.', N'7 người.', N'Cấm chở.', null, 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (75, N'Trong thùng xe dỡ hàng tự động và trên các xe chuyên dùng khác được phép trở bao nhiêu người?', N'3 người.', N'Số người cần thiết để bốc dỡ hàng.', N'Cấm chở.', null, 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (76, N'Khi điều khiển xe chạy trên đường người lái xe cần mang theo các loại giấy tờ gì về người và xe?', N'Giấy phép lái xe, đăng ký xe, giấy phép lưu hành xe.', N'Giấy phép lái xe, đăng ký xe, giấy vận chuyển, chứng minh nhân dân.', N'Lệnh vận chuyển, đăng ký xe, giấy phép lưu hành xe.', N'Giấy phép lái xe phù hợp với loại xe đó, giấy đăng ký xe, giấy chứng nhận kiểm định kỹ thuật và giấy phép vận chuyển (nếu loại xe đó cần phải có).', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (77, N'Cơ quan nào quy định danh mục hàng nguy hiểm, việc vận chuyển hàng nguy hiểm và thẩm quyền cấp giấy phép hàng nguy hiểm?', N'Bộ công an.', N'Bộ quốc phòng.', N'Chính phủ.', N'Bộ Giao thông vận tải.', 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (78, N'Trong đô thị trường hợp nào dưới đây xe không được dùng còi (trừ các xe ưu tiên theo Luật định)?', N'Khi qua nơi đông người tụ họp, đi lại trên đường.', N'Khi qua nơi có trường học trẻ em đi lại trên đường.', N'Từ 22h đến 5h sáng hôm sau.', N'Khi qua ngã ba, ngã tư, trong thành phố, thị xã, thị trấn đông người qua lại.', 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (79, N'Khi gặp một đoàn xe, một đoàn xe tang hay một đoàn người có tổ chức đi theo hàng ngũ, người lái xe phải xử lý như thế nào cho đúng quy tắc giao thông?', N'Bóp còi, rú ga để cắt ngang qua.', N'Không được cắt ngang qua đoàn xe, đoàn người.', N'Báo hiệu và từ từ cho xe đi qua để đảm bảo an toàn.', null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (80, N'Còi của xe cơ giới phải đảm bảo những yêu cầu gì?', N'Âm thanh phát ra từ xa 100m có thể nghe thấy và phát đồng giọng.', N'Âm thanh phát ra từ 50m có thể nghe thấy và phát đồng giọng.', N'Âm thanh phát ra từ xa tối thiểu 200m, nghe rõ.', null, 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (81, N'Khi muốn quay đầu xe trong trường hợp xe đang đi trên cầu, gầm cầu vượt, đường ngầm hay khu vực đường sắt giao cắt đường bộ, người lái xe phải làm gì?', N'Không được quay đầu xe.', N'Lợi dụng chỗ rộng và phải có người làm tín hiệu sau xe để đảm bảo an toàn.', N'Lợi dụng chỗ rộng có thể quay đầu được để quay đầu xe cho an toàn.', null, 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (82, N'Cơ quan nào quy định các đoạn đường cấm đi, đường đi một chiều, nơi cấm dừng, cấm đỗ, cấm quay đầu xe, lắp đặt báo hiệu đường bộ thuộc địa phương quản lý?', N'Ủy ban nhân dân cấp tỉnh.', N'Cơ quan quản lý giao thông vận tải.', N'Cảnh sát giao thông - Trật tự.', N'Thanh tra bảo vệ công trình giao thông.', 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (83, N'Để đảm bảo an toàn cho ôtô khi chuyển động, hệ thống phanh phải bảo đảm những yêu cầu nào?', N'Hiệu quả phanh cao nhất, quãng đường phanh ngắn nhất, ổn định ôtô khi phanh.', N'Điều khiển phải nhẹ nhàng, lực tác dụng lên bàn đạp phải nhỏ.', N'Không có hiện tượng bó phanh, có khả năng phanh khi ôtô đứng yên trong thời gian dài.', N'Tất cả những ý trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (84, N'Khi tập lái xe cơ giới, người lái xe phải đảm bảo những yêu cầu gì?', N'Khi tập lái xe trên đường công cộng người lái xe phải có giấy phép tập lái xe và giáo viên dạy lái ngồi bên cạnh.', N'Phải có biển "Tập lái" gắn ở phía trước và phía sau theo quy định của Bộ Giao thông vận tải.', N'Các xe ôtô chuyên dùng vào việc giảng dạy lái phải trang bị thêm bộ hãm phụ và gương phản hậu để giáo viên sử dụng khi cần thiết.', N'Tất cả các trường hợp trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (85, N'Người điều khiển ôtô tải, máy kéo có trọng tải từ 3,5 tấn trở lên. ôtô chở người từ 10 đến 30 chỗ (hạng C, D) phải đủ bao nhiêu tuổi?', N'25 tuổi.', N'21 tuổi.', N'20 tuổi.', null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (86, N'Người điều khiển xe môtô hai bánh, ba bánh có dung tích xi lanh từ 50 cm3 trở lên phải đủ bao nhiêu tuổi?', N'16 tuổi.', N'18 tuổi.', N'20 tuổi.', null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (87, N'Tại nơi có cắm biển báo "Tốc độ tối đa cho phép" những loại xe nào được chạy vượt quá số ghi trên biển báo?', N'Không loại xe nào.', N'Xe chữa cháy, xe hộ đê, xe công an, xe quân đội.', N'Xe chữa cháy, xe quân sự, xe công an, xe cứu thương.', N'Các loại xe ưu tiên theo quy định tại Điều 20 Luật giao thông đường bộ.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (88, N'Các xe chở hàng hoá, chở người có được quá trọng tải thiết kế của xe không? ', N'Được chở vượt quá trọng tải thiết kế của xe.', N'Cấm chở vượt quá trọng tải thiết kế của xe.', null, null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (89, N'Đối với xe tải nặng > 30T chạy theo đoàn, khi qua cầu hoặc dừng xe trên cầu vì gặp sự cố, phải đảm bảo khoảng cách giữa 2 xe là bao nhiêu?', N'>= 10 m.', N'>= 5 m.', N'>= 8 m.', null, 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (90, N'Người tham gia giao thông đường bộ phải có trách nhiệm gì khi nghe thấy tín hiệu của các xe ưu tiên?', N'Phải nhanh chóng giảm tốc độ, tránh hoặc dừng lại sát lề đường bên phải để nhường đường.', N'Cấm các hành vi gây cản trở xe ưu tiên.', N'Cả hai loại trách nhiệm trên.', null, 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (91, N'Xe gắn máy, môtô 2 bánh được chở nhiều nhất là mấy người?', N'Hai người kể cả người lái.', N'Ngoài người lái xe chỉ được thêm một người ngồi phía sau và một trẻ em.', N'Ngoài người lái xe được chở thêm hai người lớn trong trường hợp chở người bệnh đi cấp cứu hoặc áp giải người phạm tội.', N'Cả ý hai và ý ba.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (92, N'Tiêu chuẩn an toàn kỹ thuật quy định đối với còi điện lắp trên xe cơ giới 3 bánh, ôtô, máy kéo với âm lượng toàn bộ ở khoảng cách 2m là bao nhiêu?', N'Không nhỏ hơn 65dB(A), không lớn hơn 115dB(A).', N'Lớn hơn 75dB(A) và nhỏ hơn 100dB(A).', null, null, 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (93, N'Việc vận chuyển hàng bằng xe ôtô phải chấp hành các quy định nào?', N'Hàng vận chuyển trên xe phải được xếp đặt gọn gàng và phải được chằng buộc chắc chắn.', N'Khi vận chuyển hàng rời phải có mui, bạt che đậy không được để rơi vãi.', N'Cả hai quy định trên.', null, 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (94, N'Hàng siêu trường, siêu trọng được hiểu theo quy cách nào?', N'Hàng có kích thước hoặc trọng lượng thực tế của mỗi kiện hàng vượt quá giới hạn quy định cho phép nhưng không thể tháo rời ra được.', N'Hàng nhẹ không xếp gọn được, hàng phải dùng cần cẩu để chất lên xe, mỗi kiện hàng có trọng lượng so với thể tích vượt quá 0,6 tấn/m3.', null, null, 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (95, N'Tổ chức, cá nhân kinh doanh vận tải hàng bằng ôtô có những trách nhiệm gì?', N'Chấp hành thể lệ vận tải hàng hoá đường bộ và các quy định về đảm bảo trật tự an toàn giao thông đường bộ.', N'Chấp hành quy định riêng về vận tải, xếp dỡ, bảo quản hàng nguy hiểm, hàng siêu trường, siêu trọng.', N'Thực hiện chế độ báo cáo thống kê và các nghĩa vụ khác theo quy định của pháp luật.', N'Tất cả các trách nhiệm trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (96, N'Trong quá trình vận chuyển nếu không có người áp tải thì ai chịu trách nhiệm bảo quản hàng và bồi thường thiệt hại?', N'Chủ hàng.', N'Người vận tải.', null, null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (97, N'Bên vận tải có hay không chịu trách nhiệm bồi thường hàng chuyên chở bị biến chất do đặc điểm lý hoá tự nhiên hoặc bị thiếu ruột mà còn nguyên đai cặp chì?', N'Có chịu trách nhiệm.', N'Không chịu trách nhiệm.', null, null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (98, N'Khi vận chuyển hàng hoá quí hiếm, hàng đòi hỏi phải có kỹ thuật bảo quản chăm sóc trên đường vận chuyển có nhất thiết phải có người áp tải hoặc thuê bên vận tải làm dịch vụ áp tải không?', N'Không.', N'Có.', null, null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (99, N'Bắt buộc hay không bắt buộc người nhận hàng phải theo phương thức cân, đong, đo, đếm, nhất quán với người gửi hàng khi xếp hàng lên ôtô?', N'Theo thoả thuận.', N'Bắt buộc.', N'Không bắt buộc.', null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (100, N'Chủ phương tiện tham gia vận tải hành khách bằng xe ôtô phải chấp hành những quy định gì của Luật giao thông đường bộ?', N'Các quy định về vận chuyển hành khách.', N'Thực hiện đúng lịch trình, hành trình vận tải đã được cơ quan nhà nước có thẩm quyền phê duyệt.', N'Không được giao xe cho người không đủ điều kiện để lái xe.', N'Tất cả các quy định nói trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (101, N'Như thế nào là hình thức kinh doanh vận tải hành khách bằng xe buýt?', N'Là kinh doanh vận tải hành khách bằng ôtô theo tuyến có xác định bến đi, bến đến và xe chạy theo lịch trình hành trình quy định.', N'Là kinh doanh vận tải hành khách bằng ôtô theo tuyến cố định trong nội, ngoại thành phố, thị xã, có các điểm dừng đón, trả khách và chạy theo biểu đồ vận hành.', null, null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (102, N'Tiêu chuẩn an toàn kỹ thuật đối với bánh lốp lắp cho xe ôtô, máy kéo và các loại xe cơ giới 3 bánh được quy định như thế nào?', N'Đúng cỡ, đủ số lượng, đủ áp suất, không phồng rộp, không nứt vỡ lớp vải.', N'Bánh dẫn hướng phải đồng đều về chiều cao hoa lốp, không dùng lốp đắp.', N'Chiều cao hoa lốp còn lại không được nhỏ hơn 1,0mm đối với xe tải. 1,6mm đối với xe con và 2,0mm đối với xe khách.', N'Đảm bảo đúng các quy định trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (103, N'Hàng nguy hiểm. hàng có mùi hôi thối, súc vật đang bị dịch bệnh hoặc hàng có ảnh hưởng đến sức khoẻ của khách có được nhận chở trên xe khách không?', N'Có.', N'Cấm.', null, null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (104, N'Thế nào được gọi là tuyến vận tải khách?', N'Là tuyến đường được xác định để bố trí xe ôtô khách vận chuyển khách, đáp ứng nhu cầu khách đi lại, đi từ một điểm thuộc địa danh này đến một điểm thuộc địa danh khác.', N'Là tuyến đường quy định ôtô khách phi đi qua trên một tuyến vận tải khách với điểm đi, điểm đến, điểm dừng, điểm đỗ được xác định.', null, null, 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (105, N'Ôtô chở khách có được phép mở cửa, cho người đứng ngồi ở bậc lên xuống khi xe đang lăn bánh không?', N'Có được phép.', N'Tuyệt đối cấm.', null, null, 2);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (106, N'Xe gắn máy, mô tô chở theo ôtô khách có được chứa xăng trong bình chứa của xe hay không?', N'Phải tháo hết xăng ra khỏi bình chứa của xe.', N'Được chứa xăng trong bình chứa của xe.', null, null, 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (107, N'Cơ quan nào quy định cụ thể về việc vận chuyển hàng siêu trường, siêu trọng? ', N'Chính phủ.', N'Uỷ ban nhân dân cấp tỉnh.', N'Bộ giao thông vận tải.', null, 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (108, N'Trong thành phố, đô thị người lái xe cơ giới đường bộ phải thực hiện nhường đường cho người đi bộ và xe cơ giới khác như thế nào?', N'Nhường đường cho người đi bộ đang đi trên phần đường dành cho người đi bộ đi ngang qua đường.', N'Nhường đường cho xe cơ giới có tốc độ cao, cho xe sau xin vượt.', N'Nhường đường cho xe đi trên đường ưu tiên, đường chính bất kỳ từ hướng nào tới, nhường đường cho xe ưu tiên, cho xe từ bên phải đến, cho xe đi ở bên trái trong vòng xuyến.', N'Tất cả những trườnghợp trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (109, N'Trong thành phố, đô thị người lái xe cơ giới 3 bánh kể cả xe lam phải chấp hành những điều cấm nào (ghi ở dưới đây) khi chở hàng, chở người?', N'Cấm chở hàng hoá, hành lý trên mui xe.', N'Cấm xếp hàng hoá, hành lý nhô ra 2 bên thành xe, vượt ra phía trước và phía sau quá 1/3 chiều dài thân xe.', N'Cấm chở người, chở hàng quá tải trọng cho phép, cấm chở người ngồi cạnh người lái xe có càng điều khiển.', N'Tất cả các điều kiện trên.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (110, N'Trong thành phố, đô thị người điều khiển xe chở phân, rác, chất thải, vôi vữa, đất cát, sỏi, gạch, than, xỉ lò phải thực hiện những quy định nào (ghi dưới đây)?', N'Phải che phủ kín, không để rơi vãi, tung bụi trên đường phố. Phải có trách nhiệm thu gọn xử lý hậu quả kịp thời nếu để rơi vãi các thứ đó xuống đường phố.', N'Chỉ được hoạt động từ 22h đến 5h sáng hoặc 18h đến 6h sáng trên các tuyến đường do Uỷ ban nhân dân tỉnh, thành phố quy định.', N'Cả hai điều quy định trên.', null, 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (111, N'Biển nào cấm người đi bộ?', N'Biển 1.', N'Biển 1 và 3.', N'Biển 2.', N'Biển 2 và 3.', 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (112, N'Gặp biển nào người lái xe phải nhường đường cho người đi bộ?', N'Biển 1.', N'Biển 3.', N'Biển 2.', N'Biển 1 và 3.', 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (113, N'Biển nào chỉ đường dành cho người đi bộ, các loại xe không được đi vào khi gặp biển này?', N'Biển 1.', N'Biển 1 và 3.', N'Biển 3.', N'Cả 3 biển.', 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (114, N'Biển nào cấm mọi loại xe cơ giới đi vào, trừ xe gắn máy, mô tô 2 bánh và các loại xe ưu tiên theo luật định?', N'Biển 1.', N'Cả 3 biển', N'Biển 2.', N'Biển 1 và 3.', 1);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (115, N'Biển nào cấm ô tô tải?', N'Cả 3 biển.', N'Biển 2.', N'Biển 1 và 3.', N'Biển 1 và 2.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (116, N'Biển nào cấm máy kéo?', N'Biển 3.', N'Biển 1 và 3.', N'Cả 3 biển.', null, 3);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (117, N'Biển nào báo hiệu sắp đến chỗ giao nhau nguy hiểm?', N'Biển 1 và 2.', N'Biển 2 và 3.', N'Biển 2.', N'Cả 3 biển.', 4);
insert into Question(SttCau, CauHoi, CauA, CauB, CauC, CauD, DapAn) values (118, N'Biển nào báo hiệu sắp đến chỗ giao nhau với đường sắt?', N'Biển 1.', N'Biển 1 và 2.', N'Biển 2 và 3.', N'Cả 3 biển.', 4);
